# Generated by Django 3.0.7 on 2020-12-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaySpecial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.IntegerField()),
                ('offer', models.BooleanField(default=False)),
                ('veg', models.BooleanField(default=False)),
                ('non_veg', models.BooleanField(default=False)),
                ('best_seller', models.BooleanField(default=True)),
                ('cart', models.BooleanField(default=False)),
                ('order', models.BooleanField(default=False)),
            ],
        ),
    ]
