# Generated by Django 3.0.7 on 2020-12-20 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0002_todayspecial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images')),
                ('price', models.IntegerField(default=0)),
                ('best_seller', models.BooleanField(default=True)),
            ],
        ),
    ]
