# Generated by Django 3.0.7 on 2020-12-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
