# Generated by Django 3.0.7 on 2020-12-20 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodorder.Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
