# Generated by Django 3.0.7 on 2020-12-27 20:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0005_auto_20201223_2146'),
        ('foodorder', '0006_auto_20201220_2111'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='best_seller',
            new_name='veg',
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodorder.Product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='useraccounts.UserProfile')),
            ],
        ),
    ]
