# Generated by Django 3.0.7 on 2020-12-28 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0010_auto_20201229_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='veg',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodorder.Product'),
        ),
    ]
