# Generated by Django 3.0.7 on 2021-01-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0011_auto_20201229_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='BestSeller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('best_seller', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OfferZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Offer', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodorder.Product'),
        ),
        migrations.AddField(
            model_name='product',
            name='bestseller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodorder.BestSeller'),
        ),
        migrations.AddField(
            model_name='product',
            name='offerzone',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='foodorder.OfferZone'),
        ),
    ]
