# Generated by Django 3.0.7 on 2021-01-06 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0012_auto_20210106_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bestseller',
            name='best_seller',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='offerzone',
            name='Offer',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodorder.Product'),
        ),
    ]
