# Generated by Django 3.0.7 on 2021-01-06 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foodorder', '0019_auto_20210106_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='best_seller',
        ),
        migrations.RemoveField(
            model_name='category',
            name='offer_zone',
        ),
        migrations.AlterField(
            model_name='orders',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foodorder.Product'),
        ),
    ]
