# Generated by Django 3.0.7 on 2020-12-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='phone_no',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='age',
            new_name='phone1',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
